### PR TITLE
Add indent for anonymous function statement

### PR DESCRIPTION
**Pull request by dalugm**
e.g.

```dart
return OutlinedButton(
  onPressed: disable.value
      ? null
      : () {
          print('123123');        // Add indent here
        },
  child: Text(demo.value),
);
```

---

Besides, I didn't get it why we need a `dart-ts-mode--node-start` here, since we already have a bultin `treesit-node-start`.

https://github.com/50ways2sayhard/dart-ts-mode/blob/035484366fa9b306f52b0df5c08758969b5d50a0/dart-ts-mode.el#L91-L96

Using `back-to-indentation` may move the point to a wrong place, like the above example, when the node is `() { ...`. After using `back-to-indentation`, cursor will be move to `:`, which is not the parent of the NODE we're operating.

### CODE REVIEW

**Comment by 50ways2sayhard** [comment]
> Besides, I didn't get it why we need a dart-ts-mode--node-start here, since we already have a bultin treesit-node-start.

Finding proper indentation for children of a `block`, such as nodes within an `if_statement` or `function_body`, is convenient. However, it may not be applicable to an anonymous function.

**Comment by 50ways2sayhard** [comment]
Tested your changes locally, but the rules for `optional_formal_parameters` and `}` are not working correctly. Please double-check. Additionally, using `treesit-check-indent` is helpful for verifying the indent rules.

**Comment by dalugm** [comment]
> Additionally, using `treesit-check-indent` is helpful for verifying the indent rules

Thx, this is a useful command.

**Comment by 50ways2sayhard** [comment]
> Additionally, using treesit-check-indent is helpful for verifying the indent rules.

You can also set `treesit--indent-verbose` to `t` to log when indenting.

**Comment by dalugm** [comment]
> but the rules for `optional_formal_parameters` and `}` are not working correctly. Please double-check.

Fixed.

In the syntax tree, the prev-sibling of `optional_parameters_lists` is `,`, not `formal_parameter`.

Emmm... wrong function and bug leads to a correct result. It should be ok now

**Comment by 50ways2sayhard** [comment]
Great! I've tested it on my code and there are no more issues. If there are no further changes, please mark it as ready and I will merge it later.

**Comment by dalugm** [comment]
I have no more modifications for this pr :)

**Pull request merged**
